apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webserver-deployment.yaml
  - webserver-service.yaml
images:
  - name: nginx
    newName: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/webserver # {"$imagepolicy": "flux-system:gitops-demo:name"}
    newTag: 1.14.2 # {"$imagepolicy": "flux-system:gitops-demo:tag"}